### ISSUE TITLE
yanky.nvim causes Neovim freezing when system goes sleep

### ISSUE THREAD

**Issue by sqrtmau** [gbprod/yanky.nvim#20] opened 2022-06-06 16:36 UTC
yanky.nvim config:

```lua
require('yanky').setup({})

vim.keymap.set('n', 'p', '<Plug>(YankyPutAfter)', {})
vim.keymap.set('n', 'P', '<Plug>(YankyPutBefore)', {})
vim.keymap.set('x', 'p', '<Plug>(YankyPutAfter)', {})
vim.keymap.set('x', 'P', '<Plug>(YankyPutBefore)', {})
vim.keymap.set('n', 'gp', '<Plug>(YankyGPutAfter)', {})
vim.keymap.set('n', 'gP', '<Plug>(YankyGPutBefore)', {})
vim.keymap.set('x', 'gp', '<Plug>(YankyGPutAfter)', {})
vim.keymap.set('x', 'gP', '<Plug>(YankyGPutBefore)', {})

vim.keymap.set('n', '<c-n>', '<Plug>(YankyCycleForward)', {})
vim.keymap.set('n', '<c-p>', '<Plug>(YankyCycleBackward)', {})

require("telescope").load_extension("yank_history")
```

Neovim version:

```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

OS info:

```
OS: Arch Linux x86_64
Kernel: 5.18.1-arch1-1
DE: Plasma 5.24.5
Graphics platform: X11
```

**Comment by gbprod** [comment] 2022-06-07 07:17
Hi !
Thanks for reporting this issue.
It's pretty hard for me to debug this issue, do you have some runtime logs ?
Maybe using `vim -V9vim.log` ?

How do you know this issue comes from yanky ?

Can you try disabling `system_clipboard.sync_with_ring` option ?

**Comment by gbprod** [comment] 2022-06-09 07:19
Close as duplicate of #21

**Closed by gbprod** 2022-06-09 07:19 UTC
