### ISSUE TITLE
[Bug Report]: nvim freezing when opening files

### ISSUE THREAD

**Issue by kohane27** [gbprod/yanky.nvim#21] opened 2022-06-07 19:04 UTC
## Introduction

Hello gbprod! Big fan of your plugin series (`substitute.nvim` , `cutlass.nvim`, `yanky.nvim` (not so much due to this annoying bug)).

Since I have more than 100 plugins it's very difficult to isolate the cause of this nvim freezing. Initially it was only a hunch that `yanky` was the cause, since I can't reliably reproduce this freezing. So I disabled `yanky` and went about using nvim, no problem. Then I enabled `yanky` and nvim would freeze randomly. By freeze I mean I can't enter nvim. nvim would freeze while opening files. 

## Videos

I tried my best to isolate the cause for more than a month, and I finally captured it in video:

https://user-images.githubusercontent.com/57322459/172460874-c1ee8625-2971-46a2-bd93-d05cd39ed8e0.mp4

1. `vim init.lua`  (I have aliased vim with nvim)
2. It opened up `init.lua` without any issue
3. enabled `yanky.nvim`
4. exit nvim and `vim init.lua` again
5. nvim froze

Another video:

https://user-images.githubusercontent.com/57322459/172461797-cd99608f-c2a6-4661-8a2b-db46d15348ff.mp4

1. not shown in video: `yanky` enabled. nvim used to freeze randomly but this morning it freezes every time with `yanky` enabled
2. `vim -u NONE init.lua` to enter nvim and disable `yanky`
3. successfully entered nvim without freezing

## Description

I suspect this freezing is due to `xclip`. nvim used to freeze randomly but this morning it froze every time. The only change I have is manually compiling xclip from [xclip/master](https://github.com/astrand/xclip). I had some other issues with xclip unrelated to nvim so tested with compiling the latest version. I used to use xclip 0.13.

Interestingly, I tried `yoink.vim` and this random freezing also happened. With the advice from [vim-yoink/issues/16](https://github.com/svermeulen/vim-yoink/issues/16#issuecomment-632234373), I used `xsel` instead of `xclip` and this random freezing seemed to happen less:

severe freezing like videos above: compiling from `xclip/master`

random freezing here and there: `xclip` version 0.13 or `xsel`

The reason I used `yanky` is for its yank-ring feature. Because, sigh, my nvim would freeze randomly with the following:

1. yank buffer content
2. close nvim
3. paste yanked content to another nvim instance
4. freeze

I couldn't capture the above in video because it happens randomly.

nvim config:

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

OS: Manjaro Linux
Kernel: 5.15.41-1-MANJARO

I tried compiling nvim to the latest 0.8 version and this freezing still happened.

Any help is much appreciated. Thank you again for creating this awesome nvim plugin series:)

**Comment by gbprod** [comment] 2022-06-08 06:45
Thanks for reporting this bug. I'm working on it.

(thanks for the support ;) )

**Comment by gbprod** [comment] 2022-06-08 08:19
Ok, for the moment I can't reproduce the problem. I switch back to `xclip` to see if it will happens for me too. The only difference between you and me is that I use Debian and not Manjaro.

I think the problem comes either from the initialization of the history, or from the synchro with system clipboard.

Has this problem always been present or has it only happened since a recent yanky update? 

Can you try disabling `system_clipboard.sync_with_ring` option ? Does it still happens ?

Can you aloso try using [debug-freeze](https://github.com/gbprod/yanky.nvim/tree/debug-freeze) ?

Thanks !

**Comment by kohane27** [comment] 2022-06-08 22:16
Hello @gbprod 

Thank you for getting back to me in such short time. I appreciate it:)

> I think the problem comes either from the initialization of the history, or from the synchro with system clipboard.

Not sure if it's relevant but I also use [CopyQ](https://hluk.github.io/CopyQ).

> Has this problem always been present or has it only happened since a recent yanky update?

Always been present ever since I started using yanky.

Currently I'm trying the `debug-freeze` branch with `system_clipboard = { sync_with_ring = false }` option. I'll report back once I have any updates.

Since I have the same "freezing upon opening files" issue with `svermeulen/vim-yoink`, I just want to emphasize that this is not inherently the problem with yanky, but I thought it'd still be relevant to open an issue here.

Thank you again:)

**Comment by gbprod** [comment] 2022-06-09 07:18
> Since I have the same "freezing upon opening files" issue with `svermeulen/vim-yoink`, I just want to emphasize that this is not inherently the problem with yanky, but I thought it'd still be relevant to open an issue here.

Yes, I think so, but if I can isolate the call that triggers the freeze, maybe I can find a safier moment to make it.

Thank you for taking the time to report this issue and make some tests :sweat_smile: .

**Comment by kohane27** [comment] 2022-06-09 21:15
Hello @gbprod ! Hope you're doing well.

I'm very happy to say that after using `debug-freeze` and setting `system_clipboard = { sync_with_ring = false }`, I've been enjoying yanky without ever freezing (which never happened before); and I opened nvim dozens of time in one day.

I'm switching back to `main` with `sync_with_ring = false`. I'll keep you updated. Thank you again:)

**Comment by kohane27** [comment] 2022-06-13 12:09
hello @gbprod !

Thank you for the update! I'll test it and report back asap once I have any meaningful output:)

**Comment by kohane27** [comment] 2022-06-15 06:20
Hello @gbprod. Hope you're doing well.

Before switching to `debug-freeze` with the `schedule_wrap` function, I tried to use the `main` branch with `sync_with_ring = true` and... no freezing. And it's been 2 days. I'm baffled too :confused: 

If there's any freezing again I'll switch to `debug-freeze` and report back. Thank you again for looking into this issue. I really appreciate it:)

**Comment by gbprod** [comment] 2022-06-15 06:58
Hello !
Good news that it's not freezing any more (for the moment :sweat_smile: ). Maybe an update of your system fixed a bug with `xclip` ? ¯\_(ツ)_/¯

I keep the debug-freeze branch just in case.

I close the issue for now, fell free to reopen it !

Thanks a lot !

**Closed by gbprod** 2022-06-15 06:58 UTC
Labels: bug
